### ISSUE TITLE
Error:  Final loader didn't return a Buffer or String

### ISSUE THREAD

**Issue by fantasia949** [kossnocorp/decss-loader#1]
When trying the loader with your given minimum config, I got this error:

`./node_modules/decss/preact.js!./node_modules/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[local]-[hash:base64:5]
"}!./src/routes/home/styles.css
Module build failed: Error: Final loader didn't return a Buffer or String
    at runLoaders (D:\x\node_modules\webpack\lib\NormalModule.js:202:46)
    at D:\x\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (D:\x\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (D:\x\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at D:\x\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at runSyncOrAsync (D:\x\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (D:\x\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at iterateNormalLoaders (D:\x\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at D:\x\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at context.callback (D:\x\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.<anonymous> (D:\x\node_modules\css-loader\lib\loader.js:129:3)
    at D:\x\node_modules\css-loader\lib\processCss.js:207:3
    at <anonymous>
 @ ./src/routes/home/styles.css 4:14-129`

Did I miss something?

**Comment by kossnocorp** [comment]
It looks like a css-loader error 🤔, can you share the content of the CSS you're trying to load?

**Comment by fantasia949** [comment]
It's just simple
```css
.Button {
    color: blue;
}

.Button-disabled {
    opacity: .5;
}

.Button-color-green {
    color: green;
}
```

When I comment out 'decss/preact', webpack performs the task properly. Here is my config for css:
``` javascript
{
            test: /\.css$/,
            include: [path.resolve(__dirname, 'src')],
            use: [
                'style-loader',
                //'decss/preact', // 👈 the error occurs when I uncomment this loader
                {
                    loader: 'css-loader',
                    options: {
                        modules: true,
                        importLoaders: 1,
                        localIdentName: '[local]-[hash:base64:5]',
                    }
                },
            ]
}
```

**Comment by kossnocorp** [comment]
@fantasia949 what's the version of `decss`, `webpack` and `css-loader` you have installed? I suspect that it's version-specific problem.

**Comment by fantasia949** [comment]
``` javascript
{
    "style-loader": "^0.18.2",
    "webpack": "^3.2.0",
    "css-loader": "^0.28.4",
    "decss-loader": "^0.1.0",
}
```

Most of them are the latest version
